import Head from "next/head";
import React, { useState } from "react";

const Contact = () => {
  const [formdata, setFormdata] = useState({
    name: "",
    email: "",
    message: "",
  });
  const [resstatus, setResstatus] = useState(null);
  const [loading, setLoading] = useState(false);
  const handleFormChange = (e) => {
    setFormdata({ ...formdata, [e.target.name]: e.target.value });
  };
  const ValidateEmail = (email_id) => {
    var mailformat = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
    if (email_id.match(mailformat)) {
      return true;
    } else {
      return false;
    }
  };

  const handleContactSubmit = async (e) => {
    e.preventDefault();
    if (!ValidateEmail(formdata.email)) {
      alert("Invalid email address!");
      return;
    }
    if (formdata.name.length < 7 || formdata.message.length < 7) {
      alert("Name and mesage must be atleast 7 characters long!");
      return;
    }

    setLoading(true);

    const res = await fetch(
      "https://blogspacedata.onrender.com/api/v1/contact",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          token:
            "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNDE2NTdhMGQ1Zjg0ZTdkMTQ4ODliYyIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY2NTIzMjE4MSwiZXhwIjoxNjY1ODM2OTgxfQ.Kn663lE7GKD8hACJ2a3Vsoy7GYOS48ozuJW2hiy_Eko",
        },
        body: JSON.stringify(formdata),
      }
    );
    if (res.status === 200) {
      setFormdata({
        name: "",
        email: "",
        message: "",
      });
      setResstatus("success");
    } else {
      setResstatus("error");
    }
    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Contact - BlogSpace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font relative">
        <div className="container px-5 py-16 mx-auto">
          <div className="flex flex-col text-center w-full mb-12">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
              Contact Us
            </h1>
            <p className="lg:w-2/3 mx-auto leading-relaxed text-base">
              If you have any questions or queries I'm always be happy to help.
              Feel free to contact us by telephone or email and we will be sure
              to get back to you as soon as possible.
            </p>
          </div>
          <div className="lg:w-1/2 md:w-2/3 mx-auto">
            <div className="flex flex-wrap -m-2">
              <div className="p-2 w-1/2">
                <div className="relative">
                  <label
                    htmlFor="name"
                    className="leading-7 text-sm text-gray-600"
                  >
                    Name
                  </label>
                  <input
                    type="text"
                    id="name"
                    value={formdata.name}
                    onChange={handleFormChange}
                    name="name"
                    className="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-purple-500 focus:bg-white focus:ring-2 focus:ring-purple-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
                  />
                </div>
              </div>
              <div className="p-2 w-1/2">
                <div className="relative">
                  <label
                    htmlFor="email"
                    className="leading-7 text-sm text-gray-600"
                  >
                    Email
                  </label>
                  <input
                    type="email"
                    onChange={handleFormChange}
                    id="email"
                    value={formdata.email}
                    name="email"
                    className="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-purple-500 focus:bg-white focus:ring-2 focus:ring-purple-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
                  />
                </div>
              </div>
              <div className="p-2 w-full">
                <div className="relative">
                  <label
                    htmlFor="message"
                    className="leading-7 text-sm text-gray-600"
                  >
                    Message
                  </label>
                  <textarea
                    id="message"
                    onChange={handleFormChange}
                    name="message"
                    value={formdata.message}
                    className="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-purple-500 focus:bg-white focus:ring-2 focus:ring-purple-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"
                  ></textarea>
                </div>
              </div>

              {resstatus === "success" && (
                <div className="p-2 w-full">
                  <p className="text-xs text-green-500 mt-3 text-center">
                    Thanks for contacting us.
                  </p>
                </div>
              )}
              {resstatus === "error" && (
                <div className="p-2 w-full">
                  <p className="text-xs text-red-500 mt-3 text-center">
                    Something went wrong.
                  </p>
                </div>
              )}

              <div className="p-2 w-full">
                <button
                  className="flex mx-auto text-white bg-purple-500 border-0 py-2 px-8 focus:outline-none hover:bg-purple-600 rounded text-lg hover:drop-shadow-lg"
                  type="submit"
                  onClick={handleContactSubmit}
                >
                  {loading ? (
                    <span>
                      <img
                        className="h-7 w-7"
                        src="/loading.gif"
                        alt="Loading..."
                      />
                    </span>
                  ) : (
                    "Submit"
                  )}
                </button>
              </div>
              <div className="p-2 w-full pt-8 mt-8 border-t border-gray-200 text-center cursor-pointer">
                <a
                  href="mailto:rajeshnksingh@gmail.com"
                  className="text-purple-500"
                >
                  rajeshnksingh@gmial.com
                </a>
                <br />
                <span className="inline-flex">
                  <a
                    className="ml-4 text-gray-500"
                    href="https://github.com/devRajeshSingh"
                    target={"_blank"}
                  >
                    <svg
                      fill="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      className="w-5 h-5"
                      viewBox="0 0 24 24"
                    >
                      <path
                        fill="currentColor"
                        fillRule="evenodd"
                        d="M12.026 2c-5.509 0-9.974 4.465-9.974 9.974c0 4.406 2.857 8.145 6.821 9.465c.499.09.679-.217.679-.481c0-.237-.008-.865-.011-1.696c-2.775.602-3.361-1.338-3.361-1.338c-.452-1.152-1.107-1.459-1.107-1.459c-.905-.619.069-.605.069-.605c1.002.07 1.527 1.028 1.527 1.028c.89 1.524 2.336 1.084 2.902.829c.091-.645.351-1.085.635-1.334c-2.214-.251-4.542-1.107-4.542-4.93c0-1.087.389-1.979 1.024-2.675c-.101-.253-.446-1.268.099-2.64c0 0 .837-.269 2.742 1.021a9.582 9.582 0 0 1 2.496-.336a9.554 9.554 0 0 1 2.496.336c1.906-1.291 2.742-1.021 2.742-1.021c.545 1.372.203 2.387.099 2.64c.64.696 1.024 1.587 1.024 2.675c0 3.833-2.33 4.675-4.552 4.922c.355.308.675.916.675 1.846c0 1.334-.012 2.41-.012 2.737c0 .267.178.577.687.479C19.146 20.115 22 16.379 22 11.974C22 6.465 17.535 2 12.026 2z"
                        clipRule="evenodd"
                      />
                    </svg>
                  </a>
                  <a
                    className="ml-4 text-gray-500"
                    href="https://www.linkedin.com/in/devRajeshSingh"
                    target={"_blank"}
                  >
                    <svg
                      fill="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      className="w-5 h-5"
                      viewBox="0 0 24 24"
                    >
                      <path
                        fill="currentColor"
                        d="M19 3a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h14m-.5 15.5v-5.3a3.26 3.26 0 0 0-3.26-3.26c-.85 0-1.84.52-2.32 1.3v-1.11h-2.79v8.37h2.79v-4.93c0-.77.62-1.4 1.39-1.4a1.4 1.4 0 0 1 1.4 1.4v4.93h2.79M6.88 8.56a1.68 1.68 0 0 0 1.68-1.68c0-.93-.75-1.69-1.68-1.69a1.69 1.69 0 0 0-1.69 1.69c0 .93.76 1.68 1.69 1.68m1.39 9.94v-8.37H5.5v8.37h2.77Z"
                      />
                    </svg>
                  </a>{" "}
                  <a
                    className="ml-4 text-gray-500"
                    href="https://twitter.com/devRajeshSingh"
                    target={"_blank"}
                  >
                    <svg
                      fill="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      className="w-5 h-5"
                      viewBox="0 0 24 24"
                    >
                      <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
                    </svg>
                  </a>
                </span>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Contact;
